### ISSUE TITLE
Ошибка 5

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#527] opened 2018-05-30 10:22 UTC
**Description**
В группе во время боя появляется данная ошибка
_In the group during the battle, this error appears_

**Version Number**
5.41

**Error Log**
4x ElvUI_Enhanced-1.03\Modules\Misc\paperdoll.lua:63: attempt to index local 'frame' (a nil value)
ElvUI_Enhanced-1.03\Modules\Misc\paperdoll.lua:149: in function `?'
CallbackHandler-1.0-6:147: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
<string>:"safecall Dispatcher[2]":4: in function <[string "safecall Dispatcher[2]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[2]":13: in function `?'
CallbackHandler-1.0-6:92: in function `Fire'
AceEvent-3.0-4 (ElvUI):120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Apollyonn** [comment] 2018-06-10 12:04
Duplicate of https://github.com/ElvUI-WotLK/ElvUI_Enhanced/issues/34

**Closed by Apollyonn** 2018-06-10 12:04 UTC
