### ISSUE TITLE
Version Check : Issue continues

### ISSUE THREAD

**Issue by silentwinter** [ElvUI-WotLK/ElvUI#255] opened 2016-09-18 20:15 UTC
http://imgur.com/a/mUcRn

**Comment by silentwinter** [comment] 2016-09-18 20:17
Also, for those who are suffering from FPS drops, I can surely confirm it is because of ElvUI, unfortunately.

The way around it so far is DISABLE ELVUI AND LOG IN TO YOUR CHARACTER, THEN ENABLE ELVUI USING ADDON CONTROL PANEL. At least for me, this bumped my FPS from 20-ish during mid-25men raid fight to static 50.

**Comment by crumdidlyumshis** [comment] 2016-09-18 20:47
Even with the latest update with version check disabled, this still persists? =O

**Comment by silentwinter** [comment] 2016-09-18 20:49
Yup.. and I actually tracked the memory usage of ElvUI, it ended up hitting 15 mb during raid.

**Comment by crumdidlyumshis** [comment] 2016-09-18 20:50
@Loaal Any suggestions?

**Comment by silentwinter** [comment] 2016-09-18 20:50
no worries bois. I am studying Lua right now. Give me some coffee.

**Comment by crumdidlyumshis** [comment] 2016-09-18 20:53
/target Silentwinter
/pass Coffee
"Crumdidlyumshis passes a cup of coffee to Silentwinter."

**Comment by silentwinter** [comment] 2016-09-18 21:03
@crumdidlyumshis  I also assume that it could be Windows 10 compatibility issue with Wotlk client as it is old as fuk. I need to look into this also.

**Comment by silentwinter** [comment] 2016-09-18 21:03
Just seems like inefficient flow of data overall.  (so general but yea)

**Comment by Loaal** [comment] 2016-09-19 03:58
I just added ability to disable this function instead of removing. Feature works as Elv intends, it sends message to hidden addon channel with version of your ElvUI on each party/raid roster change.
It can't decrease fps so much (as far as i know it can't at all).


Spamalyzer by default colorize addon/prefix to red if it doesn't contains in built-in addon list.

```
if KNOWN_PREFIXES[prefix] then
	addon_name = KNOWN_PREFIXES[prefix]
end
local known = addon_name and true or false
local display_color = known and COLOR_GREEN or COLOR_RED
```

example:
`
	/run SendAddonMessage("TEST", "123", "WHISPER", UnitName("player"));
`

YamRaidTracker2
`
	/run SendAddonMessage("YRT2", "123", "WHISPER", UnitName("player"));
`

**Comment by silentwinter** [comment] 2016-09-19 04:00
Thanks. 

I am not pointing at version check for the FPS drops, I was suspecting as one of the possible issues.

**Comment by crumdidlyumshis** [comment] 2016-09-19 04:00
I honestly have not had this issue since https://github.com/ElvUI-WotLK/ElvUI/commit/8335c8abbf3d11be663725144408f884aa2a45b2

**Comment by silentwinter** [comment] 2016-09-19 04:05
Alright I will check it out later

**Comment by silentwinter** [comment] 2016-09-19 16:39
Could it be because of Lua error?

Message: Interface\AddOns\ElvUI\core\toolkit.lua:43: assertion failed!
Time: 09/19/16 12:37:53
Count: 1
Stack: [C]: ?
[C]: in function `assert'
Interface\AddOns\ElvUI\core\toolkit.lua:43: in function `Size'
Interface\AddOns\ElvUI_AddOnSkins\addons\dbm.lua:47: in function <Interface\AddOns\ElvUI_AddOnSkins\addons\dbm.lua:12>
[C]: ?
[C]: ?
[C]: in function `ApplyStyle'
Interface\AddOns\DBM-Core\DBT.lua:425: in function <Interface\AddOns\DBM-Core\DBT.lua:373>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `CreateBar'
Interface\AddOns\DBM-Core\DBM-Core.lua:3014: in function `func'
Interface\AddOns\DBM-Core\DBM-Core.lua:618: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:611>

Locals: 
-------------------------

Had lua error disabled. Enabled them and I got 220 of these errors during the RS encounter.

**Comment by Bunny67** [comment] 2016-09-19 17:24
What is your version dbm?

**Comment by silentwinter** [comment] 2016-09-19 17:35
version 4.52u

**Comment by Bunny67** [comment] 2016-09-19 17:51
Hmm, what revision?

**Comment by silentwinter** [comment] 2016-09-19 17:54
version 4.52, core r4442

**Comment by Bunny67** [comment] 2016-09-19 17:57
This error does not ElvUI, namely AddonSkins

**Comment by silentwinter** [comment] 2016-09-19 17:59
but isn't it also developed by you...? xD

**Comment by Bunny67** [comment] 2016-09-19 18:04
This error may be fixed in ElvUI AddonSkins

**Comment by silentwinter** [comment] 2016-09-19 18:12
alright I will download the newest version! 

thanks bunny!

**Comment by Bunny67** [comment] 2016-09-26 14:12
There is now a problem?

**Comment by Bunny67** [comment] 2016-10-17 20:45
Close?

**Closed** 2016-10-17 21:00 UTC

**Comment by cocochepeau** [comment] 2018-06-14 16:49
The issue is still present. My client keep crashing after several minutes, attempting to write things to memory.. It happens in overcrowded zones like Dalaran or at the entrance of raids..

I just disabled version check as stated earlier in the discussion, will see how it goes. But my guess is it's not related to this.
