### ISSUE TITLE
Ошибка 2

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI#524] opened 2018-05-25 23:44 UTC
**Description**
Словил ошибку при заходе в игру, походу конфликт с ElvUi с аддоном [DrDamage](https://www.wowace.com/projects/dr-damage/files/480655)
_There was an error when entering the game, it is possible ElvUi conflict with the addon DrDamage_

**Version Number**
5.41

**Error Log**

1x DrDamage-r1426\DrDamage.lua:2404: attempt to call global 'GetNumGlyphs' (a nil value)
DrDamage-r1426\DrDamage.lua:587: in function `?'
AceTimer-3.0-16 (ElvUI):41: in function <...AddOns\ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:36>

Locals:
self = <table> {
 defaults = <table> {}
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:161:
 SecureHook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:336:
 Damage_critMBonus = 0
 manaBucket = false
 UPDATE_SHAPESHIFT_FORM = <function> @ DrDamage\DrDamage.lua:1963:
 UNIT_COMBO_POINTS = <function> @ DrDamage\Melee.lua:108:
 GetWeaponBuff = <function> @ DrDamage\DrDamage.lua:2859:
 IsEnabled = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:482:
 fullUpdate = false
 ScheduleTimer = <function> @ ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:108:
 SaveTooltip = <function> @ DrDamage\DrDamage.lua:2446:
 UNIT_POWER = <function> @ DrDamage\Caster.lua:134:
 RegisterMessage = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:118:
 UnregisterMessage = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:181:
 UpdateGlyphs = <function> @ DrDamage\DrDamage.lua:2402:
 hooks = <table> {}
 BuffCalc = <function> @ DrDamage\DrDamage.lua:2933:
 SetEnabledState = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:455:
 Caster_CheckBaseStats = <function> @ DrDamage\Caster.lua:107:
 GetRangedBase = <function> @ DrDamage\Melee.lua:227:
 ZONE_CHANGED_NEW_AREA = <function> @ DrDamage\DrDamage.lua:1933:
 UPDATE_MACROS = <function> @ DrDamage\DrDamage.lua:2100:
 ClearTooltip = <function> @ DrDamage\DrDamage.lua:2414:
 OnEnable = <function> @ DrDamage\DrDamage.lua:430:
 CasterCalc = <function> @ DrDamage\Caster.lua:179:
 OnInitialize = <function> @ DrDamage\DrDamage.lua:411:
 NewModule = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:266:
 Calc = <function> @ DrDamage\DrDamage.lua:2884:
 ACTIONBAR_PAGE_CHANGED = <function> @ DrDamage\DrDamage.lua:1949:
 SetShapeshift = <function> @ DrDamage\DrDamage.lua:2552:
 Melee_CheckBaseStats = <function> @ DrDamage\Melee.lua:116:
 GetLevels = <function> @ DrDamage\DrDamage.lua:2821:
 GetName = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:310:
 name = "DrDamage"
 MeleeCalc = <function> @ DrDamage\Melee.lua:359:
 Disable = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:345:
 GetAP = <function> @ DrDamage\Melee.lua:235:
 Unhook = <function> @ ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:418:
 Print = <function> @ Aesa\Libs\Ace3\AceConsole-3.0\AceConsole-3.0.lua:54:
 MatchData = <function> @ DrDamage\DrDamage.lua:103:
 LEARNED_SPELL_IN_TAB = <function> @ DrDamage\DrDamage.lua:2107:
 GetNormM = <function> @ DrDamage\Melee.lua:271:
 GetRageGain = <function> @ DrDamage\Melee.lua:322:
 Melee_RefreshConfig = <function> @ DrDamage\Melee.lua:103:
 visualChange = true
 UnregisterEvent = <function> @ Aesa\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:181:
 GetSetAmount = <function> @ DrDamage\DrDamage.lua:2364:
 SetDefaultModuleLibraries = <function> @ ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:398:
 Melee_InventoryChanged = <function> @ DrDamage\Melee.lua:152:
 DmgCalculation = <table> {}
 EnableModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAdd
  ---

**Comment by Apollyonn** [comment] 2018-06-07 02:32
Duplicate of https://github.com/ElvUI-WotLK/ElvUI/issues/495.

**Closed by Apollyonn** 2018-06-07 02:32 UTC
