### ISSUE TITLE
Can't show the Roleicon!

### ISSUE THREAD

**Issue by coolaken** [ElvUI-WotLK/ElvUI#601] opened 2019-08-22 02:21 UTC
**Description**

when in 5 man group,role icon not work.

**Version Number**

6.01

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by rokpusnik** [comment] 2019-08-22 07:23
duplicate of #599, fixed in [9a3131b](https://github.com/ElvUI-WotLK/ElvUI/commit/9a3131b741c8672f78208d6cf07ff40574e887e8)

**Closed** 2019-08-22 10:21 UTC
Labels: bug
