### ISSUE TITLE
Not so much an issue, but

### ISSUE THREAD

**Issue by jonomurphy** [ElvUI-WotLK/ElvUI#464] opened 2017-12-10 17:51 UTC
Is there any way to disable the icon that appears on top of the LEFT comparison box, the two boxes on the right?

As you can see, there's an icon above the left box when I shift click to compare.

https://imgur.com/a/ERQki

**Comment by Loaal** [comment] 2017-12-14 11:24
![image](https://user-images.githubusercontent.com/590348/33989673-587db198-e0d9-11e7-83ed-34f0a07c8f27.png)
Can't reproduce.
Probably 3rd party addon adding that icon; to make sure disable ElvUI_Enhanced icon.
![image](https://user-images.githubusercontent.com/590348/33989846-093f9744-e0da-11e7-814f-8eb5ef112986.png)
[Reason for closing](https://github.com/ElvUI-WotLK/ElvUI#i-have-a-suggestionproblem-with-elvui_pluginname-where-do-i-go)

**Closed by Loaal** 2017-12-14 11:24 UTC

**Comment by jonomurphy** [comment] 2017-12-17 03:21
Fair enough. I hovered over it with /fstack and it says:

TOOLTIP
<2>TABLE: 18326550

parent
ELVUIPARENT
Weakaura
