### ISSUE TITLE
LootSlot Error

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI#535] opened 2018-06-20 19:21 UTC
**Version Number**
5.43

**Error Log**
```
Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'LootSlot()'.
Time: 06/20/18 22:19:43
Count: 1
Stack: ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: ?
Interface\AddOns\ElvUI\modules\misc\loot.lua:71: in function <Interface\AddOns\ElvUI\modules\misc\loot.lua:58>

Locals: No locals to dump
```

**Comment by Apollyonn** [comment] 2018-06-20 19:28
Duplicate of https://github.com/ElvUI-WotLK/ElvUI/issues/532

**Closed by Apollyonn** 2018-06-20 19:28 UTC
